// Package main
// Generated by sql2struct at 2024-03-03 16:06:28
package main

import "time"

// Products Generated by sql2struct at 2024-03-03 16:06:28
type Products struct {
    Id uint32 `gorm:"column:f_id" json:"Id" db:"f_id" form:"Id"` // 商品id
    Name string `gorm:"column:f_name" json:"Name" db:"f_name" form:"Name"` // 商品名称
    Description string `gorm:"column:f_description" json:"Description" db:"f_description" form:"Description"`
    Price float64 `gorm:"column:f_price" json:"Price" db:"f_price" form:"Price"`
    Weight float32 `gorm:"column:f_weight" json:"Weight" db:"f_weight" form:"Weight"` // 商品重量（kg）
    Quantity uint32 `gorm:"column:f_quantity" json:"Quantity" db:"f_quantity" form:"Quantity"` // 商品库存数量
    IsActive int32 `gorm:"column:f_is_active" json:"IsActive" db:"f_is_active" form:"IsActive"` // 商品是否激活（0 - 未激活，1 - 激活）
    Rating float64 `gorm:"column:f_rating" json:"Rating" db:"f_rating" form:"Rating"` // 商品评分
    CreatedAt time.Time `gorm:"column:f_created_at" json:"CreatedAt" db:"f_created_at" form:"CreatedAt"` // 商品创建时间
    UpdatedAt time.Time `gorm:"column:f_updated_at" json:"UpdatedAt" db:"f_updated_at" form:"UpdatedAt"` // 商品更新时间
}

// Goods 商品表
// Generated by sql2struct at 2024-03-03 16:06:28
type Goods struct {
    Id uint32 `gorm:"column:id" json:"Id" db:"id" form:"Id"` // 商品id
    Name string `gorm:"column:name" json:"Name" db:"name" form:"Name"` // 商品名称
    Description string `gorm:"column:description" json:"Description" db:"description" form:"Description"` // 商品描述
    Price float64 `gorm:"column:price" json:"Price" db:"price" form:"Price"` // 商品价格
    Weight float32 `gorm:"column:weight" json:"Weight" db:"weight" form:"Weight"` // 商品重量（kg）
    Quantity uint32 `gorm:"column:quantity" json:"Quantity" db:"quantity" form:"Quantity"` // 商品库存数量
    IsActive int32 `gorm:"column:is_active" json:"IsActive" db:"is_active" form:"IsActive"` // 商品是否激活（0 - 未激活，1 - 激活）
    Rating float64 `gorm:"column:rating" json:"Rating" db:"rating" form:"Rating"` // 商品评分
    CreatedAt time.Time `gorm:"column:created_at" json:"CreatedAt" db:"created_at" form:"CreatedAt"` // 商品创建时间
    UpdatedAt time.Time `gorm:"column:updated_at" json:"UpdatedAt" db:"updated_at" form:"UpdatedAt"` // 商品更新时间
}

func (g *Goods) GetTableNameOfGoods() string {
    return "goods"
}

// Commodity Generated by sql2struct at 2024-03-03 16:06:28
type Commodity struct {
    Id uint32 `gorm:"column:f_id" json:"Id" db:"f_id" form:"Id"` // 商品id
    Name string `gorm:"column:f_name" json:"Name" db:"f_name" form:"Name"` // 商品名称
    Description string `gorm:"column:f_description" json:"Description" db:"f_description" form:"Description"`
    Price float64 `gorm:"column:f_price" json:"Price" db:"f_price" form:"Price"`
    Weight float32 `gorm:"column:f_weight" json:"Weight" db:"f_weight" form:"Weight"` // 商品重量（kg）
    Quantity uint32 `gorm:"column:f_quantity" json:"Quantity" db:"f_quantity" form:"Quantity"` // 商品库存数量
    IsActive int32 `gorm:"column:f_is_active" json:"IsActive" db:"f_is_active" form:"IsActive"` // 商品是否激活（0 - 未激活，1 - 激活）
    Rating float64 `gorm:"column:f_rating" json:"Rating" db:"f_rating" form:"Rating"` // 商品评分
    CreatedAt time.Time `gorm:"column:f_created_at" json:"CreatedAt" db:"f_created_at" form:"CreatedAt"` // 商品创建时间
    UpdatedAt time.Time `gorm:"column:f_updated_at" json:"UpdatedAt" db:"f_updated_at" form:"UpdatedAt"` // 商品更新时间
}
