SQL_DIR := .
SQL_FILES := $(wildcard $(SQL_DIR)/*.sql)
GO_FILES := $(patsubst $(SQL_DIR)/%.sql,%_gen.go,$(SQL_FILES))

all: $(GO_FILES)

.PHONY: clean

%_gen.go: $(SQL_DIR)/%.sql
	sql2struct -sf=$< -package="main" -with-tablename-func=true > $@

clean:
ifeq ($(OS),Windows_NT)
	del /q $(GO_FILES)
else
	rm -f $(GO_FILES)
endif
